# Generated by Django 3.0.8 on 2020-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('fname', models.CharField(max_length=24)),
                ('security', models.CharField(max_length=16)),
                ('rcode', models.PositiveIntegerField(blank=True)),
                ('docs', models.ManyToManyField(blank=True, related_name='documents', to='NoteBoat.Documents')),
            ],
        ),
    ]
