# Generated by Django 3.0.8 on 2020-08-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoat', '0005_userdata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
    ]
