# Generated by Django 3.0.8 on 2020-08-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='completion',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
