# Generated by Django 3.0.8 on 2020-08-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoat', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='completion',
        ),
    ]
