# Generated by Django 3.0.8 on 2020-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoat', '0006_remove_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='pinned',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
