# Generated by Django 3.0.8 on 2020-08-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoat', '0007_documents_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='pinned',
        ),
        migrations.AddField(
            model_name='userdata',
            name='pinned',
            field=models.ManyToManyField(blank=True, related_name='pinned', to='NoteBoat.Documents'),
        ),
    ]
