# Generated by Django 3.0.8 on 2020-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoat', '0008_auto_20200810_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='pinned',
        ),
        migrations.AddField(
            model_name='userdata',
            name='pinned',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
